import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: uuid(),
    firstName: "raman",
    lastName: "joshi",
    username: "raman",
    email: "raman@gmail.com",
    password: "test123",
    pic: "",
    link: "google.com",
    bio: "Software Engineer",
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "rahul",
    lastName: "shukla",
    username: "rahul",
    email: "rahul@gmail.com",
    password: "test123",
    pic: "",
    link: "rahulcs754.netlify.com",
    bio: "Web Developer || Youtuber || Blogger || Software Engineer",
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "piyush",
    lastName: "das",
    username: "piyush",
    email: "piyush@gmail.com",
    password: "test123",
    pic: "",
    link: "google.com",
    bio: "Software Engineer",
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "raj",
    lastName: "sharma",
    username: "raj",
    email: "raj@gmail.com",
    password: "test123",
    pic: "",
    link: "google.com",
    bio: "Software Engineer",
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "nakul",
    lastName: "sharma",
    username: "nakul",
    email: "nakul@gmail.com",
    password: "test123",
    pic: "",
    link: "google.com",
    bio: "Software Engineer",
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];
